---
- name: bridge-utils - install
  apt:
    name:
    - bridge-utils

- name: bridge br0 - configure
  copy:
    src: br0
    dest: /etc/network/interfaces.d/br0
    owner: root
    group: root
    mode: 0644
  notify: "bridge : reboot"

- name: interfaces - configure
  copy:
    src: interfaces
    dest: /etc/network/interfaces
    backup: true
    owner: root
    group: root
    mode: 0644
  notify: "bridge : reboot"
